# Generated by Django 4.2 on 2023-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('post', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
