# Generated by Django 4.2 on 2023-04-22 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webp'])]),
        ),
    ]
