# Generated by Django 4.2 on 2023-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/e/ea/No_image_preview.png'),
        ),
    ]
