# Generated by Django 4.2 on 2023-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_article', '0002_article_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/e/ea/No_image_preview.png', max_length=300),
        ),
    ]
