# Generated by Django 4.2 on 2023-05-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_article', '0002_alter_article_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_id',
        ),
    ]
