# Generated by Django 4.2 on 2023-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_article', '0003_remove_article_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
