# Generated by Django 4.2 on 2023-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_article', '0004_alter_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
